#!/bin/sh
APPDIR=`dirname $0`;
java -cp "$APPDIR/src:$APPDIR/bin:/usr/local/java/gwt-2.5.0/gwt-user.jar:/usr/local/java/gwt-2.5.0/gwt-dev.jar" com.google.gwt.i18n.tools.I18NSync -out $APPDIR/src shared.org.openelis.security.SecurityMessages -createMessages ;

